// frontend/React/owen-wilson/src/components/Table.jsx
import PropTypes from "prop-types";
import TableRow from "./TableRow";

const Table = ({ data }) => {
  return (
    <table>
      <thead>
        <tr>
          <th>Movie Name</th>
          <th>Year</th>
          <th>Audio</th>
        </tr>
      </thead>
      <tbody>
        {data.map((wow, index) => {
          return <TableRow key={wow.id} {...wow} index={index} />;
        })}
      </tbody>
    </table>
  );
};

Table.propTypes = {
  data: PropTypes.array,
};

export default Table;

// frontend/Vue/owen-wilson/src/components/Table.vue
<script setup>
import TableRow from "./TableRow.vue";

defineProps({
  data: {
    type: Array,
    required: true,
  },
});
</script>

<template>
  <table>
    <thead>
      <tr>
        <th>Movie Name</th>
        <th>Year</th>
        <th>Audio</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="wow in data" :key="wow.id">
        <TableRow :movie="wow.movie" :year="wow.year" :audio="wow.audio" />
      </tr>
    </tbody>
  </table>
</template>


<style scoped>
th {
  font-weight: bold;
}
</style>
